name: env_sc
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - python=3.10.9
  - pip
  - numpy=1.23.5
  - pandas=1.5.2
  - scipy=1.10.1
  - scikit-learn=1.2.2
  - seaborn=0.12.2
  - matplotlib=3.7.1
  - networkx=2.8.4
  - h5py=3.8.0
  - scanpy=1.9.3
  - tqdm=4.65.0
